### ISSUE TITLE
System.TypeInitializationException in CSharpMath.Rendering

### ISSUE THREAD

**Issue by FoggyFinder** [verybadcat/CSharpMath#13]
When I try to use the `Draw` method of `SkiaMathPainter` :

```csharp
painter.Draw(e.Surface.Canvas, 0f, 0f);
```

I'm getting the `System.TypeInitializationException` exception:

```bash
The type initializer for 'CSharpMath.Rendering.MathFonts' threw an exception.
```

InnerException.StackTrace:

```bash
   at Typography.OpenFont.CFF.Cff1Parser.ReadRealNumber()
   at Typography.OpenFont.CFF.Cff1Parser.ReadEntry()
   at Typography.OpenFont.CFF.Cff1Parser.ReadDICTData(Int32 len)
   at Typography.OpenFont.CFF.Cff1Parser.ReadPrivateDict()
   at Typography.OpenFont.CFF.Cff1Parser.ParseAfterHeader(UInt32 cffStartAt, BinaryReader reader)
   at Typography.OpenFont.Tables.CFFTable.ReadContentFrom(BinaryReader reader)
   at Typography.OpenFont.Tables.TableEntry.LoadDataFrom(BinaryReader reader)
   at Typography.OpenFont.OpenFontReader.ReadTableIfExists[T](TableEntryCollection tables, BinaryReader reader, T resultTable)
   at Typography.OpenFont.OpenFontReader.Read(Stream stream, ReadFlags readFlags)
   at CSharpMath.Rendering.MathFonts..cctor()
```

[MCVE](https://github.com/FoggyFinder/CSharpMathMCVE)

I have no idea what's could be reason of this behaviour, maybe I miss something important. Sample from the `CSharpMath.Forms.Example` folder works fine to me.

**Comment by Happypig375** [comment]
It is weird...
When I type `double.Parse("0.04546")` in the Watch, it throws FormatException but not when I try it in the C# Interactive.

**Comment by FoggyFinder** [comment]
> When I type double.Parse("0.04546") in the Watch, it throws FormatException but not when I try it in the C# Interactive.

Could it be different settings for culture? (for float-point separator)

**Comment by FoggyFinder** [comment]
The behaviour is not related to the CSharpMath, so I'll close the issue.

**Comment by FoggyFinder** [comment]
Just to history: [#134](https://github.com/LayoutFarm/Typography/issues/134)
